package com.grinder.net.codec.login

/**
 * @author Tom <rspsmods@gmail.com>
 */
enum class LoginResultType(val id: Int) {
    ACCEPTABLE(0),
    LOGIN_SUCCESSFUL(3),
    LOGIN_INVALID_CREDENTIALS(2),
    LOGIN_DISABLED_ACCOUNT(4),
    REVISION_MISMATCH(6),
    LOGIN_DISABLED_COMPUTER(22),
    LOGIN_DISABLED_IP(27),
    LOGIN_ACCOUNT_ONLINE(5),
    LOGIN_GAME_UPDATE(6),
    LOGIN_WORLD_FULL(7),
    LOGIN_CONNECTION_LIMIT(9),
    LOGIN_BAD_SESSION_ID(30),
    LOGIN_REJECT_SESSION(11),
    INVALID_CREDENTIALS_COMBINATION(28),
    OLD_CLIENT_VERSION(30),
    LOGIN_ACCOUNT_LOCKED(35),
    SEND_UID(40)
}