package com.grinder.game.entity.agent.combat.attack.weapon.ranged;

import com.grinder.game.entity.agent.player.Player;
import com.grinder.game.entity.agent.player.equipment.EquipmentConstants;
import com.grinder.game.model.Graphic;
import com.grinder.game.model.GraphicHeight;
import com.grinder.game.model.item.Item;
import com.grinder.game.model.item.container.player.Equipment;
import com.grinder.util.ItemID;

import java.util.*;

import static com.grinder.game.entity.agent.combat.attack.weapon.ranged.Ammunition.*;

/**
 *
 * @author Stan van der Bend
 * @since 5-4-19
 */
public enum RangedWeapon {

    CRYSTAL_BOW(RangedWeaponType.CRYSTAL_BOW, new int[]{4212, 4214, 4215, 4216, 4217, 4218, 4219, 4220, 4221, 4222, 4223, 11748, 11749, 11750, 11751, 11752, 11753, 11754, 11755, 11756, 11757, 11758}, CRYSTAL_ARROW),
    BOFA(RangedWeaponType.CRYSTAL_BOW, new int[]{25865, 25862}, CRYSTAL_ARROW),
    CRAWS_BOW(RangedWeaponType.CRAWS_BOW, new int[]{22547, 22550}, CRAWS_ARROW),
    LONGBOW(RangedWeaponType.LONGBOWS, new int[]{839}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3),
    SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{841}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3),
    OAK_LONGBOW(RangedWeaponType.LONGBOWS, new int[]{845}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3),
    OAK_SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{843}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3),
    WILLOW_LONGBOW(RangedWeaponType.LONGBOWS, new int[]{847, 10280}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3),
    WILLOW_SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{849}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3),
    TRAINING_BOW(RangedWeaponType.SHORTBOWS, new int[]{ItemID.TRAINING_BOW}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3),
    FIRESOUL_SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{15719}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, OGRE_ARROWS),

    MAPLE_LONGBOW(RangedWeaponType.LONGBOWS, new int[]{851}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3),
    MAPLE_SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{853}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3),
    YEW_LONGBOW(RangedWeaponType.LONGBOWS, new int[]{855, 10282}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, ICE_ARROW, BROAD_ARROW),
    YEW_SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{857}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, ICE_ARROW, BROAD_ARROW),
    MAGIC_LONGBOW(RangedWeaponType.LONGBOWS, new int[]{859, 10284}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW),
    MAGIC_SHORTBOW(RangedWeaponType.SHORTBOWS, new int[]{861, 6724, 12788, 15433, 20558}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW),
    RAIN_BOW(RangedWeaponType.SHORTBOWS, new int[]{23357}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW),

    SEERCULL(RangedWeaponType.SEERCULL_BOW, new int[]{6724}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW),

    //GODBOW(new int[]{20997, 19143, 19149, 19146}, new Ammunition[]{Ammunition.BRONZE_ARROW, Ammunition.BRONZE_ARROW_P1, Ammunition.BRONZE_ARROW_P2, Ammunition.BRONZE_ARROW_P3, Ammunition.IRON_ARROW, Ammunition.IRON_ARROW_P1, Ammunition.IRON_ARROW_P2, Ammunition.IRON_ARROW_P3, Ammunition.STEEL_ARROW, Ammunition.STEEL_ARROW_P1, Ammunition.STEEL_ARROW_P2, Ammunition.STEEL_ARROW_P3, Ammunition.MITHRIL_ARROW, Ammunition.MITHRIL_ARROW_P1, Ammunition.MITHRIL_ARROW_P2, Ammunition.MITHRIL_ARROW_P3, Ammunition.ADAMANT_ARROW, Ammunition.ADAMANT_ARROW_P1, Ammunition.ADAMANT_ARROW_P2, Ammunition.ADAMANT_ARROW_P3, Ammunition.RUNE_ARROW, Ammunition.RUNE_ARROW_P1, Ammunition.RUNE_ARROW_P2, Ammunition.RUNE_ARROW_P3, Ammunition.BROAD_ARROW, Ammunition.DRAGON_ARROW, Ammunition.DRAGON_ARROW_P1, Ammunition.DRAGON_ARROW_P2, Ammunition.DRAGON_ARROW_P3}, RangedWeaponType.SHORTBOW),
    //ZARYTE_BOW(new int[]{20171}, new Ammunition[]{Ammunition.BRONZE_ARROW, Ammunition.BRONZE_ARROW_P1, Ammunition.BRONZE_ARROW_P2, Ammunition.BRONZE_ARROW_P3, Ammunition.IRON_ARROW, Ammunition.IRON_ARROW_P1, Ammunition.IRON_ARROW_P2, Ammunition.IRON_ARROW_P3, Ammunition.STEEL_ARROW, Ammunition.STEEL_ARROW_P1, Ammunition.STEEL_ARROW_P2, Ammunition.STEEL_ARROW_P3, Ammunition.MITHRIL_ARROW, Ammunition.MITHRIL_ARROW_P1, Ammunition.MITHRIL_ARROW_P2, Ammunition.MITHRIL_ARROW_P3, Ammunition.ADAMANT_ARROW, Ammunition.ADAMANT_ARROW_P1, Ammunition.ADAMANT_ARROW_P2, Ammunition.ADAMANT_ARROW_P3, Ammunition.RUNE_ARROW, Ammunition.RUNE_ARROW_P1, Ammunition.RUNE_ARROW_P2, Ammunition.RUNE_ARROW_P3, Ammunition.BROAD_ARROW, Ammunition.DRAGON_ARROW, Ammunition.DRAGON_ARROW_P1, Ammunition.DRAGON_ARROW_P2, Ammunition.DRAGON_ARROW_P3}, RangedWeaponType.SHORTBOW),
    TWISTED_BOW(RangedWeaponType.TWISTED_BOW, new int[]{20997, 15023, 15736, 15772, 15696, 15737, 15744, 15843, 15857, 15908, 15925, 15927, 15929, 15934, 15936, 15938, 15988, 15996, 15998, 16026, 16018, 16052, 16054, 16110}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW, DRAGON_ARROW, DRAGON_ARROW_P1, DRAGON_ARROW_P2, DRAGON_ARROW_P3),
    THIRD_AGE_BOW(RangedWeaponType.THIRD_AGE_BOW, new int[]{12424}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW, DRAGON_ARROW, DRAGON_ARROW_P1, DRAGON_ARROW_P2, DRAGON_ARROW_P3),
    DOGRESHUUN_CROSSBOW(RangedWeaponType.DORGESHUUN_CBOW, new int[]{8880}, BONE_BOLT),
    OGRE_BOW(RangedWeaponType.COMPOSITE_BOWS, new int[]{2883}, BRONZE_BRUTAL_ARROW, IRON_BRUTAL_ARROW, STEEL_BRUTAL_ARROW, BLACK_BRUTAL_ARROW, MITHRIL_BRUTAL_ARROW, ADAMANT_BRUTAL_ARROW, RUNE_BRUTAL_ARROW, OGRE_ARROWS),
    COMP_OGRE_BOW(RangedWeaponType.COMP_OGRE_BOW, new int[]{4827}, BRONZE_BRUTAL_ARROW, IRON_BRUTAL_ARROW, STEEL_BRUTAL_ARROW, BLACK_BRUTAL_ARROW, MITHRIL_BRUTAL_ARROW, ADAMANT_BRUTAL_ARROW, RUNE_BRUTAL_ARROW, OGRE_ARROWS),
    WILLOW_COMPOSITE_BOW(RangedWeaponType.COMPOSITE_BOWS, new int[]{10280}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3),
    YEW_COMPOSITE_BOW(RangedWeaponType.COMPOSITE_BOWS, new int[]{10282}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, ICE_ARROW, BROAD_ARROW),
    MAGIC_COMPOSITE_BOW(RangedWeaponType.COMPOSITE_BOWS, new int[]{10284}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, AMETHYST_ARROW, AMETHYST_ARROW_P1, AMETHYST_ARROW_P2, AMETHYST_ARROW_P3, ICE_ARROW, BROAD_ARROW),


    DARK_BOW(RangedWeaponType.DARK_BOW, new int[]{11235, 15223, 12765, 12766, 12767, 15804, 12768, 20408}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, DRAGON_ARROW, DRAGON_ARROW_P1, DRAGON_ARROW_P2, DRAGON_ARROW_P3),
    DRAGON_HUNTER_BOW(RangedWeaponType.DRAGON_HUNTER_BOW, new int[]{15804}, BRONZE_ARROW, BRONZE_ARROW_P1, BRONZE_ARROW_P2, BRONZE_ARROW_P3, IRON_ARROW, IRON_ARROW_P1, IRON_ARROW_P2, IRON_ARROW_P3, STEEL_ARROW, STEEL_ARROW_P1, STEEL_ARROW_P2, STEEL_ARROW_P3, MITHRIL_ARROW, MITHRIL_ARROW_P1, MITHRIL_ARROW_P2, MITHRIL_ARROW_P3, ADAMANT_ARROW, ADAMANT_ARROW_P1, ADAMANT_ARROW_P2, ADAMANT_ARROW_P3, RUNE_ARROW, RUNE_ARROW_P1, RUNE_ARROW_P2, RUNE_ARROW_P3, DRAGON_ARROW, DRAGON_ARROW_P1, DRAGON_ARROW_P2, DRAGON_ARROW_P3),

    HUNTER_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{10156}, KEBBIT_BOLT, LONG_KEBBIT_BOLT),
    BRONZE_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{9174}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3),
    IRON_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{9177, 767}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3),
    STEEL_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{9179}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT),
    MITHRIL_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{9181}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT),
    ADAMANT_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{9183}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT, ADAMANT_BOLT, ADAMANT_BOLT_P1, ADAMANT_BOLT_P2, ADAMANT_BOLT_P3, SAPPHIRE_BOLT, ENCHANTED_SAPPHIRE_BOLT, EMERALD_BOLT, ENCHANTED_EMERALD_BOLT, RUBY_BOLT, ENCHANTED_RUBY_BOLT),
    RUNE_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{9185, 15224, 26486}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT, ADAMANT_BOLT, ADAMANT_BOLT_P1, ADAMANT_BOLT_P2, ADAMANT_BOLT_P3, SAPPHIRE_BOLT, ENCHANTED_SAPPHIRE_BOLT, EMERALD_BOLT, ENCHANTED_EMERALD_BOLT, RUBY_BOLT, ENCHANTED_RUBY_BOLT, RUNITE_BOLT, RUNITE_BOLT_P1, RUNITE_BOLT_P2, RUNITE_BOLT_P3, BROAD_BOLT, AMETHYST_BROAD_BOLT, DIAMOND_BOLT, ENCHANTED_DIAMOND_BOLT, ONYX_BOLT, ENCHANTED_ONYX_BOLT, DRAGONSTONE_BOLT, ENCHANTED_DRAGON_BOLT),
    ARMADYL_CROSSBOW(RangedWeaponType.ARMADYL_CROSSBOW, new int[]{11785, 15225}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT, ADAMANT_BOLT, ADAMANT_BOLT_P1, ADAMANT_BOLT_P2, ADAMANT_BOLT_P3, SAPPHIRE_BOLT, ENCHANTED_SAPPHIRE_BOLT, EMERALD_BOLT, ENCHANTED_EMERALD_BOLT, RUBY_BOLT, ENCHANTED_RUBY_BOLT, RUNITE_BOLT, RUNITE_BOLT_P1, RUNITE_BOLT_P2, RUNITE_BOLT_P3, BROAD_BOLT, AMETHYST_BROAD_BOLT, DIAMOND_BOLT, ENCHANTED_DIAMOND_BOLT, ONYX_BOLT, ENCHANTED_ONYX_BOLT, DRAGONSTONE_BOLT, ENCHANTED_DRAGON_BOLT, DRAGON_BOLT, DRAGON_BOLT_P1, DRAGON_BOLT_P2, DRAGON_BOLT_P3, ENCHANTED_OPAL_DRAGON_BOLT, ENCHANTED_JADE_DRAGON_BOLT, ENCHANTED_PEARL_DRAGON_BOLT, ENCHANTED_TOPAZ_DRAGON_BOLT, ENCHANTED_SAPPHIRE_DRAGON_BOLT, ENCHANTED_EMERALD_DRAGON_BOLT, ENCHANTED_RUBY_DRAGON_BOLT,
    	    ENCHANTED_DIAMOND_DRAGON_BOLT, ENCHANTED_DRAGON_DRAGON_BOLT, ENCHANTED_ONYX_DRAGON_BOLT, OPAL_DRAGON_BOLT, JADE_DRAGON_BOLT, PEARL_DRAGON_BOLT, TOPAZ_DRAGON_BOLT, SAPPHIRE_DRAGON_BOLT, EMERALD_DRAGON_BOLT,
    	    RUBY_DRAGON_BOLT, DIAMOND_DRAGON_BOLT, DRAGON_DRAGON_BOLT, ONYX_DRAGON_BOLT),
    DRAGON_HUNTER_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{21012, 25916, 25918}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT, ADAMANT_BOLT, ADAMANT_BOLT_P1, ADAMANT_BOLT_P2, ADAMANT_BOLT_P3, SAPPHIRE_BOLT, ENCHANTED_SAPPHIRE_BOLT, EMERALD_BOLT, ENCHANTED_EMERALD_BOLT, RUBY_BOLT, ENCHANTED_RUBY_BOLT, RUNITE_BOLT, RUNITE_BOLT_P1, RUNITE_BOLT_P2, RUNITE_BOLT_P3, BROAD_BOLT, AMETHYST_BROAD_BOLT, DIAMOND_BOLT, ENCHANTED_DIAMOND_BOLT, ONYX_BOLT, ENCHANTED_ONYX_BOLT, DRAGONSTONE_BOLT, ENCHANTED_DRAGON_BOLT, DRAGON_BOLT, DRAGON_BOLT_P1, DRAGON_BOLT_P2, DRAGON_BOLT_P3, ENCHANTED_OPAL_DRAGON_BOLT, ENCHANTED_JADE_DRAGON_BOLT, ENCHANTED_PEARL_DRAGON_BOLT, ENCHANTED_TOPAZ_DRAGON_BOLT, ENCHANTED_SAPPHIRE_DRAGON_BOLT, ENCHANTED_EMERALD_DRAGON_BOLT, ENCHANTED_RUBY_DRAGON_BOLT,
    	    ENCHANTED_DIAMOND_DRAGON_BOLT, ENCHANTED_DRAGON_DRAGON_BOLT, ENCHANTED_ONYX_DRAGON_BOLT, OPAL_DRAGON_BOLT, JADE_DRAGON_BOLT, PEARL_DRAGON_BOLT, TOPAZ_DRAGON_BOLT, SAPPHIRE_DRAGON_BOLT, EMERALD_DRAGON_BOLT,
    	    RUBY_DRAGON_BOLT, DIAMOND_DRAGON_BOLT, DRAGON_DRAGON_BOLT, ONYX_DRAGON_BOLT),
    DRAGON_CROSSBOW(RangedWeaponType.CROSSBOWS, new int[]{21902}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT, ADAMANT_BOLT, ADAMANT_BOLT_P1, ADAMANT_BOLT_P2, ADAMANT_BOLT_P3, SAPPHIRE_BOLT, ENCHANTED_SAPPHIRE_BOLT, EMERALD_BOLT, ENCHANTED_EMERALD_BOLT, RUBY_BOLT, ENCHANTED_RUBY_BOLT, RUNITE_BOLT, RUNITE_BOLT_P1, RUNITE_BOLT_P2, RUNITE_BOLT_P3, BROAD_BOLT, AMETHYST_BROAD_BOLT, DIAMOND_BOLT, ENCHANTED_DIAMOND_BOLT, ONYX_BOLT, ENCHANTED_ONYX_BOLT, DRAGONSTONE_BOLT, ENCHANTED_DRAGON_BOLT, DRAGON_BOLT, DRAGON_BOLT_P1, DRAGON_BOLT_P2, DRAGON_BOLT_P3, ENCHANTED_OPAL_DRAGON_BOLT, ENCHANTED_JADE_DRAGON_BOLT, ENCHANTED_PEARL_DRAGON_BOLT, ENCHANTED_TOPAZ_DRAGON_BOLT, ENCHANTED_SAPPHIRE_DRAGON_BOLT, ENCHANTED_EMERALD_DRAGON_BOLT, ENCHANTED_RUBY_DRAGON_BOLT,
    	    ENCHANTED_DIAMOND_DRAGON_BOLT, ENCHANTED_DRAGON_DRAGON_BOLT, ENCHANTED_ONYX_DRAGON_BOLT, OPAL_DRAGON_BOLT, JADE_DRAGON_BOLT, PEARL_DRAGON_BOLT, TOPAZ_DRAGON_BOLT, SAPPHIRE_DRAGON_BOLT, EMERALD_DRAGON_BOLT,
    	    RUBY_DRAGON_BOLT, DIAMOND_DRAGON_BOLT, DRAGON_DRAGON_BOLT, ONYX_DRAGON_BOLT),
    ZARYTE_CROSSBOW(RangedWeaponType.ARMADYL_CROSSBOW, new int[]{ItemID.ZARYTE_CROSSBOW}, BRONZE_BOLT, BRONZE_BOLT_P1, BRONZE_BOLT_P2, BRONZE_BOLT_P3, OPAL_BOLT, ENCHANTED_OPAL_BOLT, IRON_BOLT, IRON_BOLT_P1, IRON_BOLT_P2, IRON_BOLT_P3, JADE_BOLT, ENCHANTED_JADE_BOLT, STEEL_BOLT, STEEL_BOLT_P1, STEEL_BOLT_P2, STEEL_BOLT_P3, PEARL_BOLT, ENCHANTED_PEARL_BOLT, MITHRIL_BOLT, MITHRIL_BOLT_P1, MITHRIL_BOLT_P2, MITHRIL_BOLT_P3, TOPAZ_BOLT, ENCHANTED_TOPAZ_BOLT, ADAMANT_BOLT, ADAMANT_BOLT_P1, ADAMANT_BOLT_P2, ADAMANT_BOLT_P3, SAPPHIRE_BOLT, ENCHANTED_SAPPHIRE_BOLT, EMERALD_BOLT, ENCHANTED_EMERALD_BOLT, RUBY_BOLT, ENCHANTED_RUBY_BOLT, RUNITE_BOLT, RUNITE_BOLT_P1, RUNITE_BOLT_P2, RUNITE_BOLT_P3, BROAD_BOLT, AMETHYST_BROAD_BOLT, DIAMOND_BOLT, ENCHANTED_DIAMOND_BOLT, ONYX_BOLT, ENCHANTED_ONYX_BOLT, DRAGONSTONE_BOLT, ENCHANTED_DRAGON_BOLT, DRAGON_BOLT, DRAGON_BOLT_P1, DRAGON_BOLT_P2, DRAGON_BOLT_P3, ENCHANTED_OPAL_DRAGON_BOLT, ENCHANTED_JADE_DRAGON_BOLT, ENCHANTED_PEARL_DRAGON_BOLT, ENCHANTED_TOPAZ_DRAGON_BOLT, ENCHANTED_SAPPHIRE_DRAGON_BOLT, ENCHANTED_EMERALD_DRAGON_BOLT, ENCHANTED_RUBY_DRAGON_BOLT,
            ENCHANTED_DIAMOND_DRAGON_BOLT, ENCHANTED_DRAGON_DRAGON_BOLT, ENCHANTED_ONYX_DRAGON_BOLT, OPAL_DRAGON_BOLT, JADE_DRAGON_BOLT, PEARL_DRAGON_BOLT, TOPAZ_DRAGON_BOLT, SAPPHIRE_DRAGON_BOLT, EMERALD_DRAGON_BOLT,
            RUBY_DRAGON_BOLT, DIAMOND_DRAGON_BOLT, DRAGON_DRAGON_BOLT, ONYX_DRAGON_BOLT),

    BRONZE_DART(RangedWeaponType.DARTS, new int[]{806, 812, 5628, 5635}, Ammunition.BRONZE_DART),
    IRON_DART(RangedWeaponType.DARTS, new int[]{807, 813, 5629, 5636}, Ammunition.IRON_DART),
    STEEL_DART(RangedWeaponType.DARTS, new int[]{808, 814, 5630, 5637}, Ammunition.STEEL_DART),
    BLACK_DART(RangedWeaponType.DARTS, new int[]{3093, 3094, 5631, 5638}, Ammunition.BLACK_DART),
    MITHRIL_DART(RangedWeaponType.DARTS, new int[]{809, 815, 5632, 5639}, Ammunition.MITHRIL_DART),
    ADAMANT_DART(RangedWeaponType.DARTS, new int[]{810, 816, 5633, 5640}, Ammunition.ADAMANT_DART),
    RUNE_DART(RangedWeaponType.DARTS, new int[]{811, 817, 5634, 5641}, Ammunition.RUNE_DART),
    AMETHYST_DART(RangedWeaponType.DARTS, new int[]{25849, 25851, 25855, 25857}, Ammunition.AMETHYST_DART),
    DRAGON_DART(RangedWeaponType.DARTS, new int[]{11230, 11231, 11233, 11234}, Ammunition.DRAGON_DART),

    BRONZE_KNIFE(RangedWeaponType.KNIVES, new int[]{864, 870, 5654}, Ammunition.BRONZE_KNIFE),
    IRON_KNIFE(RangedWeaponType.KNIVES, new int[]{863, 871, 5655}, Ammunition.IRON_KNIFE),
    STEEL_KNIFE(RangedWeaponType.KNIVES, new int[]{865, 872, 5656}, Ammunition.STEEL_KNIFE),
    BLACK_KNIFE(RangedWeaponType.KNIVES, new int[]{869, 874, 5658}, Ammunition.BLACK_KNIFE),
    MITHRIL_KNIFE(RangedWeaponType.KNIVES, new int[]{866, 873, 5657}, Ammunition.MITHRIL_KNIFE),
    ADAMANT_KNIFE(RangedWeaponType.KNIVES, new int[]{867, 875, 5659}, Ammunition.ADAMANT_KNIFE),
    RUNE_KNIFE(RangedWeaponType.KNIVES, new int[]{868, 876, 5660, 5667}, Ammunition.RUNE_KNIFE),
    DRAGON_KNIFE(RangedWeaponType.KNIVES, new int[]{22804}, Ammunition.DRAGON_KNIFE),
    DRAGON_KNIFE_P(RangedWeaponType.KNIVES, new int[]{22806, 22808, 22810}, DRAGON_KNIFE_P1),

    BRONZE_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{800}, Ammunition.BRONZE_THROWNAXE),
    IRON_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{801}, Ammunition.IRON_THROWNAXE),
    STEEL_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{802}, Ammunition.STEEL_THROWNAXE),
    MITHRIL_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{803}, Ammunition.MITHRIL_THROWNAXE),
    ADAMANT_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{804}, Ammunition.ADAMANT_THROWNAXE),
    RUNE_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{805}, Ammunition.RUNE_THROWNAXE),
    DRAGON_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{20849}, Ammunition.DRAGON_THROWNAXE),
    MORRIGANS_THROWNAXE(RangedWeaponType.THROWING_AXES, new int[]{22634}, Ammunition.MORRIGANS_THROWNAXE),
    MORRIGANS_JAVELIN(RangedWeaponType.THROWING_AXES, new int[]{22636}, Ammunition.MORRIGANS_JAVELIN),

    CHINCHOMPA(RangedWeaponType.CHINCHOMPA, new int[]{ItemID.CHINCHOMPA_2}, Ammunition.CHINCHOMPA),
    RED_CHINCHOMPA(RangedWeaponType.CHINCHOMPA, new int[]{ItemID.RED_CHINCHOMPA_2}, Ammunition.RED_CHINCHOMPA),
    BLACK_CHINCHOMPA(RangedWeaponType.CHINCHOMPA, new int[]{ItemID.BLACK_CHINCHOMPA}, Ammunition.BLACK_CHINCHOMPA),

    SWAMP_LIZARD(RangedWeaponType.LIZARD, new int[] { ItemID.SWAMP_LIZARD }, GUAM_TAR),
    ORANGE_SALAMANDER(RangedWeaponType.SALAMANDER, new int[] { ItemID.ORANGE_SALAMANDER }, MARRENTILL_TAR),
    RED_SALAMANDER(RangedWeaponType.SALAMANDER, new int[] { ItemID.RED_SALAMANDER }, TARROMIN_TAR),
    BLACK_SALAMANDER(RangedWeaponType.SALAMANDER, new int[] { ItemID.BLACK_SALAMANDER }, HARRALANDER_TAR),

    TOKTZ_XIL_UL(RangedWeaponType.TOKTZ_XIL_UL, new int[]{6522}, Ammunition.TOKTZ_XIL_UL),

    KARILS_CROSSBOW(RangedWeaponType.KARILS_CROSSBOW, new int[]{4734, 4934, 4935, 4936, 4937}, BOLT_RACK),

    BALLISTA(RangedWeaponType.BALLISTA, new int[]{19478, 15022, 19481, 26712},
            BRONZE_JAVELIN, BRONZE_JAVELIN_P1, BRONZE_JAVELIN_P2, BRONZE_JAVELIN_P3,
            IRON_JAVELIN, IRON_JAVELIN_P1, IRON_JAVELIN_P2, IRON_JAVELIN_P3,
            STEEL_JAVELIN, STEEL_JAVELIN_P1, STEEL_JAVELIN_P2, STEEL_JAVELIN_P3,
            ADAMANT_JAVELIN, ADAMANT_JAVELIN_P1, ADAMANT_JAVELIN_P2, ADAMANT_JAVELIN_P3,
            RUNE_JAVELIN, RUNE_JAVELIN_P1, RUNE_JAVELIN_P2, RUNE_JAVELIN_P3,
            DRAGON_JAVELIN, DRAGON_JAVELIN_P1, DRAGON_JAVELIN_P2, DRAGON_JAVELIN_P3,
            AMETHYST_JAVELIN, AMETHYST_JAVELIN_P1, AMETHYST_JAVELIN_P2, AMETHYST_JAVELIN_P3),

    TOXIC_BLOWPIPE(RangedWeaponType.TOXIC_BLOWPIPE, new int[]{12926, 15834}, Ammunition.DRAGON_DART, DRAGON_DART_P1, DRAGON_DART_P2, DRAGON_DART_P3, Ammunition.RUNE_DART, RUNE_DART_P1, RUNE_DART_P2, RUNE_DART_P3,
            Ammunition.ADAMANT_DART, ADAMANT_DART_P1, ADAMANT_DART_P2, ADAMANT_DART_P3, Ammunition.MITHRIL_DART, MITHRIL_DART_P1, MITHRIL_DART_P2, MITHRIL_DART_P3,
            Ammunition.STEEL_DART, STEEL_DART_P1, STEEL_DART_P2, STEEL_DART_P3, Ammunition.IRON_DART, IRON_DART_P1, IRON_DART_P2, IRON_DART_P3, Ammunition.BRONZE_DART, BRONZE_DART_P1, BRONZE_DART_P2, BRONZE_DART_P3),

    SHAYZIEN_TOXIC_BLOWPIPE(RangedWeaponType.TOXIC_BLOWPIPE, new int[]{15834}, Ammunition.DRAGON_DART, DRAGON_DART_P1, DRAGON_DART_P2, DRAGON_DART_P3, Ammunition.RUNE_DART, RUNE_DART_P1, RUNE_DART_P2, RUNE_DART_P3,
    Ammunition.ADAMANT_DART, ADAMANT_DART_P1, ADAMANT_DART_P2, ADAMANT_DART_P3, Ammunition.MITHRIL_DART, MITHRIL_DART_P1, MITHRIL_DART_P2, MITHRIL_DART_P3,
    Ammunition.STEEL_DART, STEEL_DART_P1, STEEL_DART_P2, STEEL_DART_P3, Ammunition.IRON_DART, IRON_DART_P1, IRON_DART_P2, IRON_DART_P3, Ammunition.BRONZE_DART, BRONZE_DART_P1, BRONZE_DART_P2, BRONZE_DART_P3);



    /**
     * A map of items and their respective interfaces.
     */
    public static Map<Integer, RangedWeapon> rangedWeapons = new HashMap<>();

    public static RangedWeapon[] MAGIC_BOWS = {MAGIC_SHORTBOW, MAGIC_LONGBOW};

    public static Set<Ammunition> CROSSBOW_AMMUNITION = new HashSet<>();

    static {
        for (RangedWeapon data : RangedWeapon.values()) {
            for (int i : data.getWeaponIds()) {
                rangedWeapons.put(i, data);
            }
            if(data.getType().isCrossbow()){
                CROSSBOW_AMMUNITION.addAll(Arrays.asList(data.ammunitionData));
            }
        }
    }

    private final int[] weaponIds;
    private final Ammunition[] ammunitionData;
    private final RangedWeaponType type;

    RangedWeapon(RangedWeaponType type, int[] weaponIds, Ammunition... ammunitionData) {
        this.weaponIds = weaponIds;
        this.ammunitionData = ammunitionData;
        this.type = type;
    }

    public static RangedWeapon getFor(Player p) {
        return getFor(p.getEquipment());
    }

    public static RangedWeapon getFor(Equipment equipment) {
        final Item weaponItem = equipment.atSlot(EquipmentConstants.WEAPON_SLOT);
        if(weaponItem == null)
            return null;
        final int weapon = weaponItem.getId();
        return rangedWeapons.get(weapon);
    }

    public int[] getWeaponIds() {
        return weaponIds;
    }

    public boolean isNotCompatible(Ammunition ammunition){
        for(Ammunition entry: ammunitionData){
            if(entry == ammunition)
                return false;
        }
        return true;
    }

    public Ammunition[] getAmmunitionData() {
        return ammunitionData;
    }

    public RangedWeaponType getType() {
        return type;
    }

    public int getNumberOfHits(){
        if (this == DARK_BOW)
            return 2;
        else
            return 1;
    }

    public int getHitTickInterval(){
        if(this == DARK_BOW)
            return 1;
        else
            return 0;
    }

    public boolean ignoreAttackStats(){
        return false;
    }
}
