package com.grinder.game.content.miscellaneous;

import com.grinder.game.entity.agent.player.PlayerUtil;
import com.grinder.util.Misc;

public class Announcement {

	public static String currentMessage;

	/*
	 * Random Message Data
	 */
	private static final String[][] SERVER_ANNOUNCEMENTS = {
			//{ "@whi@Make sure your account is safe, add a bank pin and security e-mail to your account!" },
			{ "@whi@Help the server out by voting every 12 hours!" },
			{ "@whi@Completing a skilling task rewards a lot of money!" },
			{ "@whi@You get bonus 500k gp and 1k blood money for every daily login streak count. 10 Days login streak equals 5m gp and 10k EXTRA blood money." },
			{ "@whi@Need a specific guide? Type ::guides" },
			{ "@whi@Did you know killing NPC's in the Wilderness gives a higher rare drop rate chance!" },
			{ "@whi@Combine your Slayer helmet with any of Fire cape, Infernal cape, or Scythe of Vitur for a great upgrade." },
			{ "@whi@Want to PK without a risk? visit the Fun PvP zone with your buddy!" },
			{ "@whi@Enchanted dragonstone bolts are the best bolts in-game." },
			{ "@whi@You can use the ::autotype to auto type and message for buying and selling." },
			{ "@whi@Your prime location for leveling Prayer is Ectofuntus, followed up by the Gilded Altar or Chaos Altar in the Wilderness!" },
			{ "@whi@Type ::commands to find a list of commands that you are eligible to use!" },
			{ "@whi@You can toggle the ability to automatically destroy vials upon consuming the last dose, instead of them being empty." },
			{ "@whi@Extra cash? Sell your items to the OSRS store for quick cash!" },
			{ "@whi@Skilling tasks are a good way to level up faster. You can get a task by speaking with a skill task master!" },
			{ "@whi@You can buy yell tokens from the general store at Edgeville which will allow you to use ::yell command." },
			{ "@whi@Always use a unique password that you do not use anywhere else for your safety!" },
			{ "@whi@Wilderness stalls gives much more cash than the average stalls at home!" },
			{ "@whi@Feeling Lucky? Check out the lottery at Edgeville by speaking with the Gambler!" },
			{ "@whi@Boss contracts at Edgeville can reward generous amount of money! Give it a try cause why not?" },
			{ "@whi@You can rarely miss a hit when training at Experiments Area!" },
			//{ "@whi@Max all your skills 250m EXP and get $100.00 voucher!" },
			{ "@whi@You can type ::osrs to exchange your cash into OSRS tokens! Each token is worth 1M on Oldschool Runescape." },
			{ "@whi@If your account ever get locked, you can always type ::unlock to verify your account details on Discord!" },
			{ "@whi@Not sure for an item price? Check out the price checker!" },
			{ "@whi@Claim your Avernic defender from the Warriors Guild minigame!" },
			{ "@whi@Each piece of prospector's set gives 10% bonus mining XP!" },
			{ "@whi@Each piece of angler's set gives 10% bonus fishing XP!" },
			{ "@whi@Customize your Yell from the Yell Customizer in the quest tab. You can choose any color of your choice." },
			{ "@whi@Did you know you can recolor your Colorful max cape to any color of your choice?" },
			{ "@whi@Check out all boss drops tables from your quest tab" },
			{ "@whi@You can search for any NPC or item drop using the Item Drop Finder in your quest tab!" },
			{ "@whi@If you love small details then you have come to the right server. We care about the smallest details." },
			{ "@whi@Woodcutting skillcape gives 30% bonus woodcutting XP!" },
			{ "@whi@Mining skillcape gives 40% bonus mining XP!" },
			{ "@whi@Fishing skillcape gives 30% bonus fishing XP!" },
			{ "@whi@Thieving skillcape gives 30% bonus thieving XP!" },
			{ "@whi@Smithing skillcape gives 30% bonus smithing XP!" },
			{ "@whi@Each piece of prospector's set gives 10% bonus mining XP!" },
			{ "@whi@Each piece of rogue's set gives 15% bonus thieving XP!" },
			{ "@whi@Each piece of rogue's set reduces the chance to be caught while pickpocketing by 15%!" },
			{ "@whi@Dodgy necklace gives 25% bonus thieving XP, and allows faster thieving!" },
			{ "@whi@Gloves of silence gives 5% bonus thieving XP, and chance to double steal!" },
			{ "@whi@Want fast money? Check out Wilderness thieving in skilling teleports!" },
			{ "@whi@Having an issue with a staff member? You can report it on Discord!" },
			{ "@whi@You can buy a Firecape from the Tokkul store at Fight Cave." },
			{ "@whi@Claim your double XP ring from the skilling points exchange for 750 points!" },
			{ "@blu@Void set, Firecape, Defenders, and many other items are tradeable!" },
			{ "@whi@You can exchange 1 voting point for 1M cash at Edgeville vote store." },
			{ "@whi@Why not finish some of your tasks in the quest tab for great rewards?" },
			{ "@whi@There are over 25 challenging bosses for you to defeat!" },
			{ "@whi@You can exchange 5 voting points for 5,000 Blood money at Edgeville vote store." },
			{ "@whi@Did you know that reaching an EXP above 50M will grant you cash rewards?" },
			{ "@whi@Crystal keys are used to open Crystal chest at Edgeville for superior rewards." },
			{ "@whi@Claim your rewards instantly from the Mystery box." },
			{ "@whi@Train your slayer for fast combat and non combat skilling." },
			//{ "@whi@Did you know that all experience gains are halved after skill level of 92!" },
			{ "@whi@Training your Magic skill using the High alchemy spell is a common way for maxing out." },
			{ "@whi@Slaying monsters in the Wilderness can reward you with a bonus Larran's key drop for Larran's chest loot." },
			{ "@whi@Did you know all doors are supported and working on Grinderscape?" },
			{ "@whi@Be careful from Al-Kharid desert heat. Make sure to take some waterskins or desert gear." },
			{ "@whi@You can use the Magic carpets from Al-Kharid to travel faster in the desert. Member's get discounted ride fees." },
			{ "@whi@Did you try knocking on the door in Varrock's west bank?" },
			{ "@whi@Did you know dying above level 20 in the Wilderness with breakable items causes them to vanish?" },
			{ "@whi@Did you know your Chinchompas run away upon death even if they are kept on death?" },
			{ "@whi@There are two custom spells in Grinderscape with unique effects! Undead Bash & Demon Agony. Check them out!" },
			{ "@whi@Did you know players get 25% increased experience when skilling in the Wilderness Resource Area?" },
			{ "@whi@You can have your own in-game title from the Title chooser in your quest tab. You can also purchase VIP titles." },
			{ "@whi@You can check your account statistics from your information tab." },
			{ "@whi@Check all the Wilderness activity using your Wilderness tab." },
			{ "@whi@You can teleport to your Wilderness target to ambush your target!" },
			{ "@whi@You can exchange your Coins with Platinum tokens by using a Bank booth." },
			{ "@whi@Did you know players with Member's rank have their Prayer drain slower depending on the rank?" },
			{ "@whi@Did you know players with Member's rank have a lot of benefits? Type ::benefits to see them all!" },
			{ "@whi@Claim your Hydro cape with its amazing stats from the Aquais Neige minigame. Surive the 30 waves." },
			{ "@whi@Using a cannon is the easiest way to max out your Ranging skill. Purchase one from Nulodion in the home area." },
			{ "@whi@Some bosses are weak to Crush attack styles, while others are weak to spears! Learn how to use your weapons!" },
			{ "@whi@Can you defeat Obor boss? Obtain a Giant key from Hill giants and enter the boss lair!" },
			{ "@whi@Dorgeshuun cross bow with Bone bolts is a commonly and cheap weapon used to train Ranged skill." },
			{ "@whi@You can trade bonds with other players where each bond is worth $50.00 redeemable on your account." },
			{ "@or2@Did you ever try training by using Salamandars?" },
			{ "@or2@Chinchompas provide great Ranged experience when attacking multiple targets at once such as Bandits or Monkeys!" },
			{ "@or2@You can unlock boss tasks from Slayer rewards." },
			{ "@or2@Did you know there are Slayer-task only areas for hassle free training?" },
			{ "@or2@Grab your Slayer Wilderness tasks from Krystilia in Edgeville home area." },
			{ "@or2@Pickpocketing Master farmer in Yanille provides quick and easy Thieving experience." },
			{ "@or2@Did you know there are over 96 different stores in-game? They are spread in the game good luck finding them all." },
			{ "@or2@Colorful items are items that can be recolored into any color of your choice at any time." },
			{ "@or2@Be careful from the Market guards when stealing from stalls." },
			{ "@or2@Did you take a look the the Slayer points store in slayer rewards? A lot of items awaiting you." },
			{ "@or2@You can receive bonus unique items when thieving from the Miscellenous stall!" },
			{ "@or2@Did you ever try the Warriors guild minigame in the 2nd floor? It's great for quick experience." },
			{ "@or2@Did you speak to our AI bot Oneiromancer in the home area? She is very sweet." },
			{ "@or2@Ruby bolts (e) provide enormous Ranged experience when used against JAD or high hit points bosses!" },
			{ "@or2@Did you collect all the Gilded items collection in-game?" },
			{ "@whi@Iron Man can buy from any store spread in game except for shops area. For example, Dragon scim from Ape Atoll Dungeon hidden store." },
			{ "@or2@You can fill your water fillable items from any water source in-game." },
			{ "@or2@Don't forget your light source when going into dark areas." },
			{ "@or2@Did you know using a Saradomin's light will permanently glow the Zamorak chamber boss room in God wars?" },
			{ "@or2@Did you collect all the obtainable pets collection in-game?" },
			{ "@or2@Shop now and get yourself that desired equipment!" },
			{ "@or2@If you want to enjoy Grinderscape to the max play on Full screen with music and sounds enabled!" },
			{ "@or2@Did you know Grinderscape has been online since 2008? Check it out!" },
			{ "@or2@Don't forget to join our Discord events for daily rewards and OSRS give-aways!" },
			{ "@or2@Did you know wearing a Fairy ring+ can transform you into a rock crab?" },
			{ "@whi@Did you know players get 25% increased experience when skilling in the Wilderness Resource Area?" },
			{ "@whi@Mage's book increases magic attack accuracy by 25%!" },
			{ "@whi@Master's wand increases magic attack accuracy by 15%!" },
			{ "@whi@Staff of Light increases magic attack accuracy by 15%!" },
			{ "@whi@Occult necklace increases magic damage dealt by up to 10%!" },
			{ "@whi@Light and Dark mystic robes gives double stats compared to the blue mystic." },
			{ "@whi@Skilling in the Wilderness grants 50% bonus XP for non combat skills." },
			{ "@whi@Wearing Ahrim's set increases your magic attack accuracy by 20%!" },
			//{ "@whi@Who will win, Saradomin or Zamorak? watch the fight at Castle Wars!" },
			{ "@whi@Need help from a staff member? do ::staffonline and don't hesitate to ask!" },
			{ "@whi@Can you defeat the almighty Jad? claim your firecape now!" },
			{ "@whi@You can press TAB to alternate and reply your previous private messages." },
			{ "@whi@Smithing skillcape increases your smithing XP while equipped!" },
			{ "@whi@Amulet of eternal glory has double the stats compared to the normal glory!" },
			{ "@whi@Did you know players get 25% increased experience when skilling in the Wilderness Resource Area?" },
			{ "@whi@Wilderness champion amulet is the best amulet in-game for PKing!" },
			{ "@whi@The more bananas in your inventory the stronger the banana's whip special attack!" },
			{ "@whi@Using rune pouch is a great way to save up some runes space in your inventory!" },
			{ "@whi@Bonecrusher makes it very easy to level up prayer!" },
			{ "@whi@Did you know leveling up your combat skills rewards you with great cash to get your journey started?" },
			{ "@whi@Vote daily to accumulate vote streaks and get awesome rewards!" },
			{ "@whi@Make sure to join us on Discord for latest updates and news!" },
			{ "@whi@Be the winner of voting contest and get awesome rewards!" },
			//{ "@whi@Vote to gain Vote Sortition credits and roll awesome rewards!" },
			{ "@whi@You can note your items by using an item on a bank booth!" },
			{ "@whi@Ring of wealth increases your rare drop chance by 8%!" },
			{ "@whi@Not sure of an item's market price? Use the in-game price checker!" },
			{ "@whi@Type ::updates to view the latest server updates!" },
			{ "@whi@Banana whip special attack can be used to skull your opponent in the Wilderness" },
			{ "@whi@Rose whip special attack can be used to disable protect one item to your opponent for 3 minutes!" },
			{ "@whi@Indigo whip special attack freezes your opponent for 6 seconds!" },
			{ "@whi@Dragon whip can be made by combining dragon's tail with an abyssal's whip!" },
			{ "@whi@Skills reward you items and skilling points that can be used at skilling shop!" },
	};

	private static final String[][] STORE_ANNOUNCEMENTS = {
			{ "@or2@Want to achieve your goal? Shop now and gain many extra advantages!" },
			{ "@or2@Looking for an elite armor? Shop now and have access to exclusive equipments!" },
			{ "@or2@Shop now and get yourself that desired equipment!" },
			{ "@or2@You can view the Mystery boxes reward by speaking with Premium Points Store!" },
			{ "@or2@The Limited Items shop will never restock on those items and they can only be obtained from the store." },
			{ "@or2@Get yourself that Member rank and gain up to 22 exclusive features!" },
			{ "@or2@Did you know? By purchasing from us, it helps to keep the game running!" },

	};

	public static void sequence() {
		currentMessage = SERVER_ANNOUNCEMENTS[Misc.getRandomInclusive(SERVER_ANNOUNCEMENTS.length - 1)][0];
		PlayerUtil.broadcastMessage("<img=759> " + currentMessage);
	}

	public static void sequence2() {
		currentMessage = STORE_ANNOUNCEMENTS[Misc.getRandomInclusive(STORE_ANNOUNCEMENTS.length - 1)][0];
		PlayerUtil.broadcastMessage("<img=758> " + currentMessage);
	}
}