package com.grinder.util.timing;

public enum TimerKey {
	FOOD,
	KARAMBWAN,
	POTION,
	COMBAT_NEXT_ATTACK,
	FREEZE,
	FREEZE_IMMUNITY,
	STUN,
	ATTACK_IMMUNITY,
	BLOOD_SACRIFICE_TIMER,

	COMBAT_COOLDOWN,
	ATTACK_COOLDOWN,
	OVERLOAD_POTION,
	TRANSFORMATION,
	LAST_SOUND,
	LAST_PESTCONTROL_SOUND,
	BUTTON_DELAY,
	GAMBLE_BUTTON,

	CHARGE_SPELL_CAST,
	CHARGE_SPELL_EFFECT,

    FORCE_LOGOUT_TIMER,
	LAST_HEAL_COMMAND,
	LAST_SPEC_COMMAND,
	WINE_FERMENT
}
