package com.grinder.game.content.minigame.aquaisneige;

import static com.grinder.game.content.minigame.aquaisneige.Constants.*;


public enum Wave {
    _1(WATER_ELEMENTAL),
    _2(WATER_ELEMENTAL, ICEFIENDS),
    _3(WATER_ELEMENTAL, ICEFIENDS, WATER_WIZARD),
    _4(WATER_ELEMENTAL, ICEFIENDS, ICEFIENDS, WATER_WIZARD),
    _5(WATER_ELEMENTAL, WATER_ELEMENTAL_2),


    _6(ICEFIENDS, HYDRO_TROLL),
    _7(ICEFIENDS, HYDRO_TROLL, ICE_SPIDER),
    _8(ICEFIENDS, HYDRO_TROLL, ICE_SPIDER, ICE_GIANT),
    _9(ICEFIENDS, HYDRO_TROLL, HYDRO_TROLL, ICE_SPIDER, ICE_SPIDER, ICE_GIANT),
    _10(ICEFIENDS, ICEFIENDS_2),


    _11(HYDRO_TROLL, HYDRO_TROLL, HYDRO_WARRIOR),
    _12(HYDRO_TROLL, HYDRO_WARRIOR, WATER_ELEMENTAL, ICE_SPIDER),
    _13(HYDRO_TROLL, HYDRO_WARRIOR, WATER_ELEMENTAL, ICE_SPIDER, ICE_GIANT),
    _14(ICE_GIANT, HYDRO_WARRIOR, WATER_ELEMENTAL, ICE_SPIDER, HYDRO_TROLL),
    _15(HYDRO_TROLL, HYDRO_TROLL_2),


    _16(ARMAROS, WATER_ELEMENTAL),
    _17(ARMAROS, WATER_ELEMENTAL, ICEFIENDS, ICE_SPIDER, WATER_WIZARD),
    _18(ARMAROS, ICE_GIANT, HYDRO_WARRIOR, ICE_SPIDER),
    _19(ARMAROS, ICEFIENDS, WATER_WIZARD, HYDRO_WARRIOR, ICE_GIANT),
    _20(ARMAROS, ARMAROS_2),



    _21(KRAMPUS, HYDRO_WARRIOR),
    _22(KRAMPUS, ARMAROS),
    _23(KRAMPUS, ARMAROS, ICEFIENDS, ICE_SPIDER),
    _24(KRAMPUS, ARMAROS, ICEFIENDS, ICE_SPIDER, ICE_SPIDER, WATER_WIZARD),
    _25(KRAMPUS, KRAMPUS_2),


    _26(NYKUR, WATER_ELEMENTAL, HYDRO_TROLL, ICEFIENDS),
    _27(NYKUR, WATER_WIZARD, ICE_GIANT, ICEFIENDS, ICE_SPIDER),
    _28(NYKUR, HYDRO_WARRIOR, HYDRO_TROLL, ICE_SPIDER, WATER_ELEMENTAL, WATER_WIZARD),
    _29(NYKUR, NYKUR_2, KRAMPUS),

    INADEQUACY(THE_INADEQUACY);

    private final int[] ids;

    Wave(int... ids) {
        this.ids = ids;
    }

    public int asInt(){
        return ordinal()+1;
    }
    public Wave getNextWave() {
        if (this == INADEQUACY) {
            return _1;
        }
        return values()[ordinal() + 1];
    }

    public int[] getIds() {
        return ids;
    }
}
